//Metodos para los Números
const numero1 = 100;
const numero2 = 200;
const numero3 = 7;
const numero4 = 6;
const numero5 = -5;

//Llamadas a Consola
console.log(numero1);
console.log(numero2);

//Operaciones
console.log(numero1 + numero2);
console.log(numero2 - numero1);
console.log(numero2 * numero1);
console.log(numero2 / numero1);
console.log(numero3 % numero4); //Modulo, son los residuos de las divisiones(Par = 0, Impar = 1, Residuos = 2, 3, 4,etc)